// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "AR_ExplosiveBarrel.generated.h"

class UStaticMeshComponent;
class URadialForceComponent;
UCLASS()
class RE_ACTROGUELIKE_API AAR_ExplosiveBarrel : public AActor
{
	GENERATED_BODY()

protected:
	// Barrel mesh with physics simulation enabled
	UPROPERTY(VisibleAnywhere)
	UStaticMeshComponent* MeshComp;
	
	// Radial force used to simulate explosion impulse
	UPROPERTY(VisibleAnywhere)
	URadialForceComponent* ForceComp;
	
	// Bind hit event after components are initialized
	virtual void PostInitializeComponents() override;
	
	/**
 	* Handles collision events for the explosive barrel class instance.
 	* Triggers explosion impulse(logs debug information about the hit).
 	*
 	* @param HitComponent     The barrel's mesh component that received the hit.
 	* @param OtherActor       The actor that collided with the barrel.
 	* @param OtherComp        The specific component on the other actor involved in the hit.
 	* @param NormaleImpulse Physics impulse generated by the collision.
 	* @param Hit              Full hit result including impact point and surface data.
 	*/
	UFUNCTION()
	void OnActorHit(UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp,
		FVector NormaleImpulse, const FHitResult& Hit);
	
public:
	// Sets default values for this actor's properties
	AAR_ExplosiveBarrel();

protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

public:
	// Called every frame
	virtual void Tick(float DeltaTime) override;
};
