#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "Engine/EngineTypes.h"              // FHitResult
#include "Components/PrimitiveComponent.h"   // UPrimitiveComponent
#include "AR_ProjectileBase.generated.h"

// Forward declarations
class UAudioComponent;
class USphereComponent;
class UProjectileMovementComponent;
class UParticleSystemComponent;
class UParticleSystem;
class USoundCue;

UCLASS(Abstract)
class RE_ACTROGUELIKE_API AAR_ProjectileBase : public AActor
{
	GENERATED_BODY()

public:
	AAR_ProjectileBase();

protected:
	UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly, Category = "Components")
	USphereComponent* SphereComp;
    
	UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly, Category = "Components")
	UProjectileMovementComponent* MovementComp;
    
	UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly, Category = "Components")
	UParticleSystemComponent* EffectComp;
    
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Components")
	UAudioComponent* FlightAudioComp;
	
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Effects | VFX")
	UParticleSystem* ImpactVFX;
	
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Effects | Sounds&Audios")
	USoundCue* ImpactSoundCue;
	
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Effects | CameraShake")
	TSubclassOf<UCameraShakeBase> ImpactShake;
	
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Effects | CameraShake")
	float ImpactShakeInnerRadius;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Effects | CameraShake")
	float ImpactShakeOuterRadius;
	
	// Prevent duplicate Explode
	UPROPERTY(VisibleInstanceOnly, Category = "State")
	bool bExploded = false;

	/**
	* Handles overlap events for projectile instances.
	* Triggered when the projectile's collision component begins overlapping another actor.
	*
	* @param OverlappedComponent   The projectile's collision component that initiated the overlap.
	* @param OtherActor            The actor that the projectile overlapped with.
	* @param OtherComp             The specific component on the other actor involved in the overlap.
	* @param OtherBodyIndex        Index of the overlapping body (for multi-body components).
	* @param bFromSweep            Whether the overlap was caused by a sweep movement.
	* @param SweepResult           Detailed hit result when overlap is generated from a sweep.
	*/
	UFUNCTION()
	virtual void OnProjBeginOverlap(
		UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp,
		int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
	
	/**
	 * Handles collision events for the MagicProjectile class instance.
	 * Triggers explosion impulse(logs debug information about the hit).
	 *
	 * @param ComponentBeenHit The projectile's mesh component that received the hit.
	 * @param OtherActor       The actor that collided with the projectile.
	 * @param OtherComp        The specific component on the other actor involved in the hit.
	 * @param NormalImpulse    Physics impulse generated by the collision.
	 * @param Hit              Full hit result including impact point and surface data.
	 */
	UFUNCTION()
	virtual void OnProjHit(UPrimitiveComponent* ComponentBeenHit, AActor* OtherActor, 
		UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit);
	
	/**The base class is only responsible for "dead appearance" and does not force Destroy.
	* It is up to the subclass to decide whether to Destroy immediately or delay. /Teleport, etc.
	* Currently just play ImpactVFX and ImpactSoundCue if they are valid.*/
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable)
	void Explode(const FHitResult& Hit);

	virtual void PostInitializeComponents() override;

public:
	// Redundant?
	FORCEINLINE UProjectileMovementComponent* GetMovementComp() const { return MovementComp; }
};
